spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api-regex?useTimezone=true&serverTimezone=UTC
    username: root
    password: 12345678@Ta
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
spring-doc:
  pathsToMatch: /regex/**/**
  swagger-ui:
    use-root-path: true